server:
  port: 8888

#db specific properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  #ORM s/w specific properties
  jpa.hibernate.ddl-auto: update
  jpa.show-sql: true